"""Generates vdirsyncer.conf from the accounts/pairs in the UI config.

One storage is generated per (account, service). Secrets are NOT written to the
file; they are passed to the vdirsyncer subprocess as environment variables.
"""
from __future__ import annotations

import json
import re
from typing import Any

from store import storage_name

STATUS_PATH = "/data/status/"
TOKEN_DIR = "/data"

ICLOUD_CAL_URL = "https://caldav.icloud.com/"
ICLOUD_CARD_URL = "https://contacts.icloud.com/"


def _val(v: Any) -> str:
    return json.dumps(v)


def _sec_var(account_id: str, field: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9]", "_", account_id).upper()
    return f"CACS_SEC_{safe}_{field.upper()}"


def _storage_block(account_id: str, acc: dict[str, Any], service: str,
                   env: dict[str, str], read_only: bool = False) -> list[str]:
    name = storage_name(account_id, service)
    kind = acc.get("kind", "caldav")
    is_cal = service == "calendar"
    out = [f"[storage {name}]"]
    if read_only:
        out.append("read_only = true")  # one-way sync: never write to the source side

    if kind == "google":
        out.append(f'type = {_val("google_calendar" if is_cal else "google_contacts")}')
        out.append(f'token_file = {_val(f"{TOKEN_DIR}/{name}.token")}')
        for fld in ("client_id", "client_secret"):
            var = _sec_var(account_id, fld)
            env[var] = acc.get(fld, "") or ""
            out.append(f'{fld}.fetch = ["command", "printenv", "{var}"]')
    else:
        out.append(f'type = {_val("caldav" if is_cal else "carddav")}')
        if kind == "icloud":
            url = ICLOUD_CAL_URL if is_cal else ICLOUD_CARD_URL
        else:  # generic caldav/carddav (incl. Microsoft, Nextcloud, ...)
            url = acc.get("cal_url" if is_cal else "card_url", "") or ""
        out.append(f"url = {_val(url)}")
        out.append(f'username = {_val(acc.get("username", ""))}')
        var = _sec_var(account_id, "password")
        env[var] = acc.get("password", "") or ""
        out.append(f'password.fetch = ["command", "printenv", "{var}"]')
    out.append("")
    return out


def mapping_dirconf(coll: list[Any], pair: dict[str, Any]) -> tuple[str, str]:
    """Per-mapping (direction, conflict_resolution).

    Direction/conflict live on the collection entry as elements [3]/[4];
    collections saved before per-mapping settings existed fall back to the
    pair-level values, then to the defaults.
    """
    direction = (coll[3] if len(coll) >= 4 and coll[3] else None) \
        or pair.get("direction", "both")
    if direction not in ("both", "a_to_b", "b_to_a"):
        direction = "both"
    conflict = (coll[4] if len(coll) >= 5 and coll[4] else None) \
        or pair.get("conflict_resolution", "a wins")
    return direction, conflict


def generate(cfg: dict[str, Any], *, only_pair: str | None = None,
             only_collection: str | None = None,
             list_all: bool = False) -> tuple[str, dict[str, str]]:
    """Build a vdirsyncer config.

    Direction is now a *per-mapping* setting, but vdirsyncer's read_only lives on
    the (shared) storage, so a single vdirsyncer pair can't mix directions. CaCs
    therefore syncs one mapping at a time: pass ``only_collection`` and the two
    storages get read_only set from THAT mapping's direction. Without it (discover
    / mapping registration) both sides stay writable — direction is irrelevant
    there since discover never writes.
    """
    env: dict[str, str] = {}
    lines = ["# AUTO-GENERATED by CaCs – do not edit by hand.",
             "[general]", f'status_path = {_val(STATUS_PATH)}', ""]

    pairs = cfg["pairs"]
    if only_pair:
        pairs = {only_pair: pairs[only_pair]}
    accounts = cfg["accounts"]

    def _find_coll(p: dict[str, Any], short: str) -> list[Any] | None:
        for c in p.get("collections", []):
            if c and len(c) >= 3 and c[0] == short:
                return c
        return None

    # storage_name -> (account_id, service); plus which storages are frozen
    # (read_only) for the single mapping being synced.
    needed: dict[str, tuple[str, str]] = {}
    readonly: dict[str, bool] = {}
    for pid, p in pairs.items():
        svc = p.get("service", "calendar")
        sa, sb = storage_name(p["a"], svc), storage_name(p["b"], svc)
        needed[sa] = (p["a"], svc)
        needed[sb] = (p["b"], svc)
        if only_collection is not None:
            coll = _find_coll(p, only_collection)
            if coll is not None:
                direction, _ = mapping_dirconf(coll, p)
                # a_to_b: A is source -> freeze A; b_to_a: freeze B; both: neither.
                # (Never freeze both — vdirsyncer raises BothReadOnly.)
                readonly[sa] = direction == "a_to_b"
                readonly[sb] = direction == "b_to_a"

    for sname, (aid, svc) in needed.items():
        acc = accounts.get(aid)
        if acc:
            lines += _storage_block(aid, acc, svc, env,
                                    read_only=readonly.get(sname, False))

    for pid, p in pairs.items():
        svc = p.get("service", "calendar")
        sa, sb = storage_name(p["a"], svc), storage_name(p["b"], svc)
        conflict = p.get("conflict_resolution", "a wins")
        if list_all:
            colls: list[Any] = []
        elif only_collection is not None:
            coll = _find_coll(p, only_collection)
            colls = [[coll[0], coll[1], coll[2]]] if coll else []
            if coll is not None:
                _, conflict = mapping_dirconf(coll, p)
        else:
            colls = [[c[0], c[1], c[2]] for c in p.get("collections", []) if len(c) >= 3]
        lines += [
            f"[pair {pid}]",
            f"a = {_val(sa)}",
            f"b = {_val(sb)}",
            "collections = [" + ", ".join(_val(c) for c in colls) + "]",
            f'conflict_resolution = {_val(conflict)}',
            'metadata = ["displayname", "color"]' if svc == "calendar"
            else 'metadata = ["displayname"]',
            "",
        ]

    return "\n".join(lines) + "\n", env
